In [1]:
import numpy as np

X = np.load("../data/X.npy")
y = np.load("../data/y.npy")

print(X.shape)
print(y.shape)
print(np.unique(y, return_counts=True))

FileNotFoundError: [Errno 2] No such file or directory: '../data/X.npy'

In [2]:
X = np.load("../data/X.npy")
y = np.load("../data/y.npy")

FileNotFoundError: [Errno 2] No such file or directory: '../data/X.npy'

In [3]:
import numpy as np

X = np.load("../data/X.npy")
y = np.load("../data/y.npy")

print(X.shape)
print(y.shape)
print(np.unique(y, return_counts=True))

(29, 64, 801)
(29,)
(array([1, 2, 3]), array([14,  7,  8]))


In [4]:
mask = (y == 2) | (y == 3)

X_bin = X[mask]
y_bin = y[mask]

print(X_bin.shape)
print(np.unique(y_bin, return_counts=True))

(15, 64, 801)
(array([2, 3]), array([7, 8]))


In [5]:
y_bin = np.where(y_bin == 2, 0, 1)
print(np.unique(y_bin, return_counts=True))


(array([0, 1]), array([7, 8]))


In [6]:
from mne.decoding import CSP
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

X_train, X_test, y_train, y_test = train_test_split(
    X_bin, y_bin, test_size=0.3, random_state=42, stratify=y_bin
)

clf = Pipeline([
    ("csp", CSP(n_components=4, log=True, norm_trace=False)),
    ("lda", LinearDiscriminantAnalysis())
])

clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Computing rank from data with rank=None
    Using tolerance 0.0007 (2.2e-16 eps * 64 dim * 4.9e+10  max singular value)
    Estimated rank (data): 64
    data: rank 64 computed from 64 data channels with 0 projectors
Reducing data rank from 64 -> 64
Estimating class=0 covariance using EMPIRICAL
Done.
Estimating class=1 covariance using EMPIRICAL
Done.
Accuracy: 0.4
Confusion matrix:
 [[1 1]
 [2 1]]
              precision    recall  f1-score   support

           0       0.33      0.50      0.40         2
           1       0.50      0.33      0.40         3

    accuracy                           0.40         5
   macro avg       0.42      0.42      0.40         5
weighted avg       0.43      0.40      0.40         5



In [7]:
csp = clf.named_steps["csp"]
csp.plot_patterns(info=None)

NOTE: plot_patterns() is a legacy function. New code should use get_spatial_filter_from_estimator(clf, info=info).plot_patterns().


AttributeError: 'NoneType' object has no attribute '_unlock'

In [8]:
from sklearn.model_selection import StratifiedKFold, cross_val_score

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

scores = cross_val_score(clf, X_bin, y_bin, cv=cv, scoring="accuracy")
print("CV scores:", scores)
print("Mean accuracy:", scores.mean())
print("Std:", scores.std())

Computing rank from data with rank=None
    Using tolerance 0.00073 (2.2e-16 eps * 64 dim * 5.1e+10  max singular value)
    Estimated rank (data): 64
    data: rank 64 computed from 64 data channels with 0 projectors
Reducing data rank from 64 -> 64
Estimating class=0 covariance using EMPIRICAL
Done.
Estimating class=1 covariance using EMPIRICAL
Done.
Computing rank from data with rank=None
    Using tolerance 0.00074 (2.2e-16 eps * 64 dim * 5.2e+10  max singular value)
    Estimated rank (data): 64
    data: rank 64 computed from 64 data channels with 0 projectors
Reducing data rank from 64 -> 64
Estimating class=0 covariance using EMPIRICAL
Done.
Estimating class=1 covariance using EMPIRICAL
Done.
Computing rank from data with rank=None
    Using tolerance 0.00074 (2.2e-16 eps * 64 dim * 5.2e+10  max singular value)
    Estimated rank (data): 64
    data: rank 64 computed from 64 data channels with 0 projectors
Reducing data rank from 64 -> 64
Estimating class=0 covariance using EMP